name: auto-generate-gitbook
on:                                 #在main分支上进行push时触发  
  push:
    branches:
    - main

jobs:
  main-to-gh-pages:
    runs-on: ubuntu-latest
        
    steps:                          
    - name: checkout main
      uses: actions/checkout@v2
      with:
        ref: main
            
    - name: install nodejs
      uses: actions/setup-node@v1
      
    - name: configue gitbook
      run: |
        npm install -g gitbook-cli          
        gitbook install
        npm install -g gitbook-summary
                
    - name: generate _book folder
      run: |
        book sm
        gitbook build
        cp SUMMARY.md _book
                
    - name: push _book to branch gh-pages 
      env:
        TOKEN: ${{ secrets.TOKEN }}
        REF: github.com/${{github.repository}}
        MYEMAIL: jackymxp@gmail.com                  # ！！记得修改为自己邮箱
        MYNAME: ${{github.repository_owner}}          
      run: |
        cd _book
        git config --global user.email "${MYEMAIL}"
        git config --global user.name "${MYNAME}"
        echo "${MYNAME}"
        echo "${MYEMAIL}"
        git init
        # git remote add origin https://${REF}
        git remote add origin git@github.com:jackymxp/gitbook-test.git
        echo  https://${REF}
        git add . 
        git commit -m "Updated By Github Actions With Build ${{github.run_number}} of ${{github.workflow}} For Github Pages"
        echo "哈哈"
        git checkout -b gh-pages 
        git status 
        
        git push -f  --set-upstream origin gh-pages
        
        
        # echo git branch -M main finish
        # echo "https://${TOKEN}@${REF}" 
        # git push --force --quiet "https://${TOKEN}@${REF}" main:gh-pages  #强制推送到gh-pages分支
        # git push --force --quiet   git@github.com:jackymxp/gitbook-test.git   main:gh-pages 
